// glossary.js — 术语表共享模块（SOP-02：一次维护，所有公司/岗位复用）
// GLOSSARY：短解释（tooltip 悬停）；EXTRA：深挖（解释 + 高频追问 + 回答要点），覆盖同名短解释。
// 维护入口：仅需修改本文件，build.js 构建时自动注入，无需改动其他脚本。
const GLOSSARY = {
  // ===== LLM / Agent =====
  'Agent': '智能体：能自主规划、调用工具、多步推理完成任务的系统',
  'LLM': '大语言模型，如 GPT/Claude/Qwen/DeepSeek',
  'ReAct': 'Reasoning+Acting：Thought→Action→Observation 循环推理范式',
  'Orchestrator': '编排器：负责 ReAct 循环调度和工具调用流程控制的组件',
  'Critic': '批评者模块：对生成结果做校验/纠正，类似智驾诊断闭环',
  'RAG': '检索增强生成：先从知识库检索再让 LLM 生成，缓解幻觉',
  'Reranker': '重排器：对检索候选做精细相关性排序（Cross-Encoder）',
  'Embedding': '向量化：把文本/图像映射为稠密向量用于相似度检索',
  'BM25': '经典关键词检索算法，擅长专有名词/精确匹配',
  'RRF': '倒数排名融合：RRF=Σ1/(k+rank)，合并多路检索结果，k 通常取 60',
  'Cross-Encoder': '交叉编码器：把 query 和 doc 拼一起打分，精度高但无法建索引',
  'Bi-Encoder': '双编码器：query 和 doc 分别编码成向量，可建 ANN 索引',
  'Corrective RAG': '纠正式 RAG：生成后检测幻觉，不合格触发二次检索',
  'Self-RAG': '模型内化反思 token 的 RAG，需要微调',
  'GraphRAG': '基于知识图谱的 RAG，擅长跨文档多跳推理，索引成本高',
  'LLM-as-Judge': '用 LLM 当评判器：检查答案质量/幻觉/一致性',
  'Function Calling': '函数调用：让模型输出结构化 JSON 以调用外部工具',
  'Tool Use': 'Claude 的函数调用机制，tool_use/tool_result 消息块',
  'MCP': 'Model Context Protocol：连接模型与工具的标准协议（类比 USB-C）',
  'JSON Schema': 'JSON 结构定义规范，用于工具参数和输出格式约束',
  'Prompt': '提示词：发给模型的指令文本，Prompt 工程决定模型行为',
  'System Prompt': '系统提示：设定角色、工具说明、决策准则的顶层指令',
  'Prompt 注入': '攻击者把恶意指令混入输入，诱导模型越权操作',
  'CoT': '思维链 Chain-of-Thought：让模型逐步推理提升正确率',
  'MoE': '专家混合架构：总参量大但每次只激活部分参数，如 35B-A3B',
  'SFT': '监督微调：用标注数据训练模型学会特定行为',
  'token': '模型处理文本的最小单位，中文约 1 字≈1-2 token',
  'context window': '上下文窗口：模型一次能处理的 token 上限',
  '幻觉': '模型一本正经地编造不存在的答案',
  'few-shot': '少样本示例：在 prompt 里给几个例子引导模型',
  'Plan-then-Execute': '先规划再执行的两阶段 Agent 范式',
  'Reflexion': '自我反思：根据失败反馈更新记忆再重试',
  'MetaGPT': '多 Agent 协作框架，按产品/架构/开发等角色分工',
  'SSE': 'Server-Sent Events：服务端流式推送，实现打字机效果',
  'OpenAI 兼容 API': '遵循 OpenAI 接口规范的服务，可无缝切换模型后端',
  'trace': '跟踪日志：记录 Agent 每一步 Thought/Action/Observation',
  '温度': 'temperature：控制模型输出的随机性，越低越稳定',
  '降级策略': '服务异常时的兜底方案，保证核心功能可用',
  // ===== 推理/部署 =====
  'vLLM': '高吞吐大模型推理引擎，核心是 PagedAttention + Continuous Batching',
  'PagedAttention': 'KV Cache 分页管理，类比 OS 虚拟内存，减少显存碎片',
  'Continuous Batching': '连续批处理：请求级动态调度，提升 GPU 利用率',
  'KV cache': '推理时缓存历史 key/value 加速生成，占显存大头',
  '量化': '降低权重精度省显存加速推理，如 INT4/INT8/FP8',
  'INT4': '4bit 权重量化（0.5 byte/参数），权重存储理论省约 75%',
  'GPTQ': 'GPT 提出的 4bit 训练后权重量化（基于 Hessian 逆矩阵逐层误差补偿）',
  'AWQ': '激活感知量化：按激活分布挑选重要权重通道保护（INT4）',
  'GGUF': 'llama.cpp 生态的量化模型格式',
  'bitsandbytes': 'PyTorch 量化库，支持 INT4/INT8 加载',
  'TTFT': '首 token 延迟：从请求到输出第一个 token 的时间',
  'VRAM': '显存：GPU 上的高速内存',
  'P99': '99% 请求延迟上限，衡量长尾延迟',
  'QPS': '每秒查询数，衡量服务吞吐',
  'Speculative Decoding': '推测解码：小模型草稿+大模型验证，降低延迟',
  'TensorRT-LLM': 'NVIDIA 高性能推理引擎，支持 INT8/FP8 量化',
  'flash_attn': 'Flash Attention：减少 HBM 读写加速注意力计算',
  'SDPA': 'PyTorch 内置的缩放点积注意力，flash_attn 缺失时的备选',
  'NCCL': 'NVIDIA 多 GPU 通信库，分布式训练/推理的关键依赖',
  'RPC': '远程过程调用：跨进程/跨机调用函数',
  'CUDA': 'NVIDIA GPU 编程平台，模型部署的基础环境',
  'Docker': '容器化技术：打包环境依赖，保证部署一致性',
  'docker-compose': '多容器编排工具，一键启动整套服务',
  'Gradio': '快速搭建 AI 模型 Web 界面的 Python 库',
  'FastAPI': '高性能 Python Web 框架，常用作模型服务 API 层',
  'LangChain': 'LLM 应用开发框架，提供 Chain/Agent 等组件',
  'Orin': 'NVIDIA 车载计算平台（Orin X 254TOPS），智驾主流算力芯片',
  'Snapdragon Ride': '高通智驾计算平台',
  'distillation': '知识蒸馏：大模型教小模型，压缩部署成本',
  // ===== 自动驾驶 / 系统 =====
  '感知': '看懂环境：检测障碍物、车道线、交通标志等',
  '规划': '决策走哪：生成轨迹，如 A*/Lattice/MPC',
  '控制': '执行动作：转向/油门/刹车，如 PID/LQR/MPC',
  '定位': '知道在哪：SLAM/RTK+IMU/GNSS 组合定位',
  '端到端': '传感器原始输入直接输出动作，消除模块化误差传递',
  '一段式端到端': '传感器直接→轨迹输出（如 UniAD/VAD），无中间感知结果',
  '二段式端到端': '感知结果→轨迹输出，保留感知中间表示',
  '模块化': '感知→预测→规划→控制分模块实现，可解释但误差传递',
  'VLA': 'Vision-Language-Action：视觉+语言输入直接输出动作',
  'D2D': 'Door-to-Door：从家门口到目的地全场景端到端方案',
  'BEV': '鸟瞰视角感知表示，统一多相机视角到俯视图',
  'Occupancy Network': '占据网络：预测 3D 空间每个体素的占据/语义',
  'UniAD': '业界著名一段式端到端模型（规划导向）',
  'VAD': '向量化场景表示的一段式端到端模型',
  '世界模型': '学习环境物理规律的模型，用于仿真/预测/强化学习',
  '强化学习': '让模型在环境中试错学习最优策略',
  '物理AI': 'AI 落地物理世界的理念：感知-决策-控制与物理环境交互',
  '诊断闭环': '检测异常→定位根因→降级恢复→验证→归档',
  '故障降级': '系统故障时的安全处理：安全停车/降级运行/静默',
  'Fail-Safe': '故障后进入安全状态（如减速停车）',
  'Fail-Operational': '故障后仍保持最低功能运行（L3+ 必须）',
  'Fail-Silent': '故障后静默失效（不上报错误）',
  '功能仲裁': '多模块冲突决策时的裁决机制',
  '模式切换': '系统在手动/辅助/自动等模式间的切换',
  'OTA': '远程升级：通过无线网络更新车辆软件，A/B 分区防变砖',
  'A/B 分区': '双系统分区：升级失败可回滚旧版本',
  'ISO 26262': '汽车功能安全国际标准，ASIL A-D 分级',
  'ASIL': '汽车安全完整性等级 A→D，D 最严苛',
  'SOTIF': '预期功能安全 ISO 21448：解决算法能力不足问题',
  'HARA': '危害分析与风险评估：确定 ASIL 等级的方法',
  'FMEA': '失效模式与影响分析：自下而上找故障影响',
  'FTA': '故障树分析：从顶层危害倒推故障原因',
  'FMEDA': '失效模式与诊断覆盖分析：算 SPFM/LFM/PMHF',
  'MRC': '最小风险机动：降级时的安全停车策略',
  'AEB': '自动紧急制动：碰撞预警时主动刹车',
  'NOA': '领航辅助驾驶：高速/城区的点到点辅助',
  'corner case': '边缘场景：罕见但危险的交通情况',
  '接管率': '每百公里驾驶员接管次数，衡量系统成熟度',
  'L2': '部分自动驾驶：驾驶员需随时接管',
  'L3': '有条件自动驾驶：系统运行时可脱手，需随时接管',
  'L4': '高度自动驾驶：限定区域内无需驾驶员',
  'BSP': '板级支持包：硬件与操作系统的适配层',
  'SoC': '片上系统：整合 CPU/GPU/NPU 的车载计算芯片',
  'Tier1': '一级供应商：向整车厂提供系统级部件',
  'OEM': '整车厂（原始设备制造商）',
  'ECU': '电子控制单元：车内的微型计算机',
  'T-BOX': '远程通信终端：车辆联网/OTA 的入口',
  '域控制器': '按功能域（智驾/座舱/车身）集中的控制器',
  '中央计算': '整车算力集中到一个高性能计算平台',
  '区域控制器': '按物理区域分布的控制器，连接传感器与中央',
  'E/E 架构': '电子电气架构：整车通信与供电的总体设计',
  'Bootloader': '引导加载程序：启动固件/刷写程序的入口',
  '灰度发布': '分批放量升级，监控异常即回滚',
  'A 样件': '产品原型样件（Alpha 样件），参与开发意味着深入项目核心',
  'V 模型': '汽车软件开发流程：需求→设计→实现→验证对应',
  'ASPICE': '汽车软件过程改进标准，规范开发流程',
  'MIL/SIL/HIL': '模型在环/软件在环/硬件在环：层层验证手段',
  'VIL': '车辆在环：实车+仿真的测试方式',
  // ===== 通信 / AUTOSAR =====
  'CAN': '传统车载总线：低带宽高可靠，一帧最多 8 字节',
  'CAN FD': 'CAN 升级版：一帧 64 字节，速率更高',
  'LIN': '低端车载总线：车窗/座椅等简单控制',
  'Ethernet': '车载以太网：高带宽，支撑智驾数据流',
  'SOME/IP': '服务化通信协议（SOA）：Client/Server + 事件通知',
  'DDS': '分布式发布订阅中间件，23+ QoS 策略',
  'TSN': '时间敏感网络：保证车载以太网实时性',
  'QoS': '服务质量：可靠性/延迟/持久性等通信保证',
  'UDS': '统一诊断服务：$10 会话/$19 读码/$22 读数据等',
  'DTC': '诊断故障码：记录车辆故障的标准编码',
  'DoIP': '基于以太网的诊断传输协议',
  'AUTOSAR': '汽车软件标准架构：CP 硬实时 + AP 高性能',
  'CP': 'AUTOSAR Classic：硬实时高安全 ECU 平台（C/RTOS）',
  'AP': 'AUTOSAR Adaptive：高性能智驾平台（C++/Linux）',
  'RTE': '运行时环境：AUTOSAR CP 应用层与 BSW 的通信桥',
  'BSW': '基础软件层：AUTOSAR CP 的 OS/通信/诊断/存储等',
  'MCAL': '微控制器抽象层：芯片厂商提供的驱动层',
  'SWC': '软件组件：AUTOSAR 应用层的最小功能单元',
  'RTOS': '实时操作系统：保证任务在确定时间内完成',
  'OSEK': 'AUTOSAR CP 用的硬实时操作系统标准',
  'POSIX': 'UNIX 系统接口标准，AP 平台基于其运行',
  'HIL 台架': '硬件在环测试台：实时机+IO 板卡+视频注入',
  // ===== 编程 / 算法 =====
  'STAR': 'Situation-Task-Action-Result：结构化讲项目的方法',
  'STARR': 'STAR+Reflection：加复盘反思的升级版',
  'RAII': '资源获取即初始化：用对象生命周期管理资源（C++）',
  'shared_ptr': 'C++ 共享所有权智能指针，引用计数管理内存',
  'unique_ptr': 'C++ 独占所有权智能指针',
  '智能指针': 'C++ 自动管理内存生命周期的指针',
  'move 语义': 'C++11 移动语义：转移资源所有权避免拷贝',
  'GIL': 'Python 全局解释器锁：限制多线程并行执行',
  'asyncio': 'Python 异步 IO 库，协程并发',
  '双指针': '算法技巧：两个指针遍历数组/字符串',
  '动态规划': '算法范式：拆子问题并复用结果',
  'NMS': '非极大值抑制：目标检测去重算法',
  'Soft-NMS': '改进 NMS：重叠框按分数衰减而非直接删除',
  'YOLO': '单阶段目标检测网络',
  'Faster R-CNN': '两阶段检测网络，RPN 生成候选框',
  'BEVFormer': 'BEV 感知 Transformer 模型',
  'Transformer': '注意力机制的深度学习架构',
  'Self-Attention': '自注意力：序列元素间相互加权',
  'SLAM': '同时定位与建图',
  'EKF': '扩展卡尔曼滤波：非线性系统状态估计',
  'KF': '卡尔曼滤波：线性系统状态估计',
  'IMU': '惯性测量单元：测量加速度与角速度',
  'RTK': '实时动态差分定位：厘米级 GNSS 定位',
  'GNSS': '全球导航卫星系统（GPS 等）',
  'MPC': '模型预测控制：滚动优化控制量',
  'LQR': '线性二次调节器：最优控制方法',
  'PID': '比例-积分-微分控制器',
  'A*': '启发式寻路算法',
  'Frenet': '沿参考线运动的坐标系，规划常用',
  'Lattice': '格点规划：离散采样轨迹再选择',
  'ST Graph': '速度-时间图：规划速度曲线用',
  'HRBP': '人力资源业务伙伴：负责面试流程与谈薪',
  '物理AI': 'AI 落地物理世界的理念：感知-决策-控制与物理环境交互',
  // ===== 新增（235B 量化 / Agent 工程） =====
  'HITL': 'Human-In-The-Loop：高风险操作由人审批确认后再执行的机制',
  'LangGraph': 'LangChain 的图状态编排框架，StateGraph 定义节点+边的 Agent 流程',
  'StateGraph': 'LangGraph 状态图：节点+边定义流程，状态可持久化',
  'Checkpointer': '状态检查点：把 Agent 对话状态持久化到外存，崩溃可恢复不丢上下文',
  '熔断器': 'Circuit Breaker：连续失败后自动熔断请求，防止故障雪崩',
  'Prometheus': '开源监控系统：采集指标、告警、查询（Grafana 可视化）',
  'TP': '张量并行：权重按卡切分、每步 all-reduce 同步的多卡推理方式',
  'all-reduce': '多卡间的权重/梯度同步通信原语',
  'Marlin': 'GPTQ 专用的高效 INT4 推理内核，A100 上有明显加速',
  'GPTQ-Int4': 'GPTQ 方法的 4bit 量化格式，约 0.5 byte/参数',
  'Tensor Core': 'GPU 专用矩阵加速单元，FP8 Tensor Core 需 H100 等新硬件',
  'disable-thinking': '关闭模型的思维链输出模式，输出更干净，利于评测解析'
};


const EXTRA = {
  // ===== LLM / Agent =====
  'Agent': '智能体：能自主规划、调用工具、多步推理完成任务的系统\n【追问】Agent 和 Chatbot 本质区别？\n答：Chatbot 单次无状态推理；Agent 有多步决策 + 反馈闭环（ReAct 循环），能调用外部工具自主完成任务\n【追问】怎么证明不是玩具？\n答：~100 条工单 manual eval：完成率 86%、工具准确率 91%；trace 全记录支持失败回溯',
  'ReAct': 'Reasoning+Acting：Thought→Action→Observation 循环推理范式\n【追问】死循环了怎么办？\n答：max_iterations=8 硬限 + 重复 Action 检测 + 降级为普通问答（最长工单约 7 步，8 有冗余）\n【追问】和 Plan-then-Execute 区别？\n答：ReAct 边想边做、灵活但可能乱序；Plan-Execute 先出整体计划再逐步执行、可控但僵硬。长流程自动拆 Plan-then-Execute',
  'Orchestrator': '编排器：负责 ReAct 循环调度和工具调用流程控制的组件\n【追问】为什么选 35B MoE 当 Orchestrator？\n答：3B 激活就够驱动 function calling（本质是分类/格式化任务），单卡常驻、成本比 70B 稠密低一个量级',
  'Critic': '批评者模块：对生成结果做校验/纠正，类似智驾诊断闭环\n【追问】为什么不每步触发？\n答：R1 Distill 的 CoT 很长，每步跑延迟翻倍到 10s+。只在工具异常信号 + 最终答案两处触发，输出 JSON {valid, reason, needs_regeneration}；Critic 挂了返回 valid:True（宁可放过不可误杀）\n【追问】和智驾诊断闭环的关系？\n答：检测异常→纠正/重试→最终校验→trace 归档，架构模式同构',
  'Reflexion': '自我反思：根据失败反馈更新记忆再重试\n【追问】和 Critic 的区别？\n答：Critic 是外部校验器判好坏；Reflexion 是失败后反思并重试的闭环。我用 R1 在工具选择歧义 + 最终答案两处做 Reflexion 式自检，非每步触发',
  'CoT': '思维链 Chain-of-Thought：让模型逐步推理提升正确率\n【追问】有什么代价？\n答：输出 token 多、延迟高。R1 的 CoT 很长（所以 Critic 不能每步触发）；Qwen3 默认思考模式还会污染评测解析（需 --disable-thinking）',
  'Function Calling': '函数调用：让模型输出结构化 JSON 以调用外部工具\n【追问】底层原理？\n答：本质是 SFT 学出来的分布偏移——模型学会输出特定 JSON 格式，不是"切换模式"\n【追问】怎么防注入？\n答：JSON Schema 入参校验 + SQL SELECT-only 白名单 + 不直接 eval 模型输出',
  'JSON Schema': 'JSON 结构定义规范，用于工具参数和输出格式约束\n【追问】为什么用它定义工具接口？\n答：接口定义与实现解耦（类似 ACR/ICD），模型侧映射 function calling，换 Claude/GPT 零改动——基于 MCP 设计理念',
  'MCP': 'Model Context Protocol：连接模型与工具的标准协议（类比 USB-C）\n【追问】和你的 JSON Schema 工具注册什么关系？\n答：MCP 是协议层标准，我的工具注册用 JSON Schema 是同一理念——接口定义和实现解耦',
  'LangChain': 'LLM 应用开发框架，提供 Chain/Agent 等组件\n【追问】为什么用 AgentExecutor 不纯手写？\n答：框架管好 ReAct 状态机、历史注入、解析等通用基建，快速搭骨架；自研集中在 Critic 触发策略、JSON Schema 工具注册、降级与 trace——框架做通用编排、我们做场景工程',
  '幻觉': '模型一本正经地编造不存在的答案\n【追问】怎么缓解？\n答：RAG 检索兜底 + Sufficient Context 校验 + Reranker 过滤低相关上下文 + Corrective RAG 二次检索 + Citation 溯源',
  'Plan-then-Execute': '先规划再执行的两阶段 Agent 范式\n【追问】你的 Agent 用在哪？\n答：长流程（查库存→报修→通知领料）自动拆 Plan：先出整体计划再逐步执行；简单咨询走 RAG 直回不进循环',
  'Prompt 注入': '攻击者把恶意指令混入输入，诱导模型越权操作\n【追问】怎么防御？\n答：入参校验、权限分层、系统提示与用户输入隔离、SQL 等工具层白名单（SELECT-only）兜底',
  'HITL': 'Human-In-The-Loop：高风险操作由人审批确认后再执行\n【追问】哪些动作进审批流？\n答：报修/下单等不可逆高风险动作人工审批，普通查询自动执行——降风险与体验的平衡（README 工程版 LG-A 有）',
  '熔断器': 'Circuit Breaker：连续失败后自动熔断请求，防止故障雪崩\n【追问】触发后怎么恢复？\n答：熔断期内快速失败 → 周期半开试探 → 恢复后关闭，配合重试 + 降级中间件使用',
  'trace': '跟踪日志：记录 Agent 每一步 Thought/Action/Observation\n【追问】有什么用？\n答：失败回溯定位（工具选择错误/Critic 误判/上下文超限）+ 每步执行可观测 + 评估集构建',
  'Prompt': '提示词：发给模型的指令文本，Prompt 工程决定模型行为\n【追问】工程化有哪些手段？\n答：few-shot 示例、结构化输出约束、温度控制（Critic 用 0.1）、系统提示角色设定、工具说明注入',
  // ===== RAG =====
  'RAG': '检索增强生成：先从知识库检索再让 LLM 生成，缓解幻觉\n【追问】为什么不让 LLM 直接回答？\n答：三大缺陷——知识截止、私有数据无法触达、幻觉\n【追问】你的完整链路？\n答：切分→Milvus 入库→gte-Qwen2-1.5B dense 召回 + BM25 混合召回 RRF→bge-reranker-v2-m3 精排→多模型路由生成→Corrective RAG 闭环→RAGAS 评估',
  'Embedding': '向量化：把文本/图像映射为稠密向量用于相似度检索\n【追问】用哪个模型？\n答：gte-Qwen2-1.5B-instruct，batch=32，1536 维稠密向量，Milvus HNSW/IP 索引；精排用 bge-reranker-v2-m3 cross-encoder（top-5，score >0.4）',
  'Reranker': '重排器：对检索候选做精细相关性排序（Cross-Encoder）\n【追问】为什么不直接用于检索？\n答：pair 级计算、无 ANN 索引能力，必须两段式——先召回 top-50 再精排 top-5\n【追问】阈值？\n答：bge-reranker-v2-m3，score >0.4 过滤低相关上下文降幻觉',
  'BM25': '经典关键词检索算法，擅长专有名词/精确匹配\n【追问】为什么混合检索必须有它？\n答：纯向量检索对专有名词/产品代号/生僻术语表达弱，BM25 关键词精确匹配兜底（金融场景长尾 query 尤其明显）',
  'RRF': '倒数排名融合：RRF=Σ1/(k+rank)，合并多路检索结果，k 通常取 60\n【追问】为什么不用分数直接相加？\n答：cosine 和 TF-IDF 分数量纲不一致，RRF 只用排名规避量纲问题（Cormack 2009 论文经验值）',
  'Cross-Encoder': '交叉编码器：把 query 和 doc 拼一起打分，精度高但无法建索引\n【追问】和 Bi-Encoder 分工？\n答：Bi-Encoder 向量化可建 ANN 索引做召回；Cross-Encoder 精排。两段式架构：先 Bi 召回再 Cross 精排',
  'Corrective RAG': '纠正式 RAG：生成后检测幻觉，不合格触发二次检索\n【追问】和 Self-RAG 区别？\n答：Self-RAG 靠模型内化反思 token（需微调）；CRAG 外部纠错无需微调。我用 CRAG 思路：LLM-as-Judge 检查证据缺失→改写 query 或扩大 top-K→重生成',
  'RAGAS': 'RAG 离线评估框架：Faithfulness / Answer Relevancy / Context Precision / Recall\n【追问】你的评估数据？\n答：离线评估集测精排后 top-5 命中率，较纯向量召回提升约 32%；定期跑 RAGAS 对比 chunk 策略与 Corrective RAG 开关的影响',
  'Milvus': '开源向量数据库，支持 dense+BM25 混合检索（HNSW 索引）\n【追问】索引参数？\n答：HNSW M=16, efC=200, efS=64，metric=IP（Milvus 百万级推荐配置）\n【追问】上线踩过什么坑？\n答：测试数据混入 collection 导致同 query 答案不一致→加 dev/prod 环境标签 + 版本号，切换自动校验',
  'HNSW': '层级可导航小世界图索引：M 边数、efC 建图质量、efS 查询精度\n【追问】参数怎么配？\n答：M=16、efC=200、efS=64；efS 调大召回好但延迟升，按延迟预算取舍',
  // ===== 推理 / 部署 / 量化 =====
  'vLLM': '高吞吐大模型推理引擎，核心是 PagedAttention + Continuous Batching\n【追问】和 Transformers pipeline 的区别？\n答：①CB 请求级动态调度 vs 静态 batch ②PagedAttention 分页管理 KV cache 防碎片 ③低并发 2-3 路约 1.5-2×、高并发（8 路并发实测）约 3×。策略：开发走 Transformers、上线走 vLLM\n【追问】max-num-seqs 怎么调？\n答：通常 256——64 以下利用率不足、512 以上显存预分配 OOM，256 是 7B-14B 在 A100 的平衡点',
  'PagedAttention': 'KV Cache 分页管理（类比 OS 虚拟内存），减少显存碎片\n【追问】为什么能提速？\n答：显存复用 + 碎片消除 → 同显存装更多请求 → batch 更大。低并发收益小（显存不紧张），高并发优势明显',
  'Continuous Batching': '连续批处理：请求级动态调度，提升 GPU 利用率\n【追问】和传统 batch 区别？\n答：传统 batch 等整批处理完再换批；CB 粒度到 iteration，请求完成即腾位给新请求，高并发优势大',
  'KV cache': '推理时缓存历史 key/value 加速生成，占显存大头\n【追问】显存怎么估算？\n答：每层每 token ≈ 2×hidden_size×2 bytes。7B 约 32 层、hidden≈4096：KV ≈16KB×8K×32 ≈4GB/序列，权重 BF16 14GB，A100 80G 够用——关键展示计算逻辑而非精确值',
  '量化': '降低权重精度省显存加速推理，如 INT4/INT8/FP8\n【追问】省多少？什么口径？\n答：两个口径要分清——纯权重理论压缩比（235B 470GB→117GB 省 75%）vs 实测总显存（14B 31.2→12.1GB 省 61%，含 KV cache/dequant workspace）',
  'INT4': '4bit 权重量化，约 0.5 byte/参数，GPTQ/AWQ 主流方法\n【追问】INT4 推理一定比 BF16 快？\n答：不一定。dequantization 开销在低并发（<4 路）下接近 BF16；Marlin 内核高并发才显优势（2-3×）',
  'GPTQ': 'GPT 提出的 4bit 训练后权重量化（基于 Hessian 逆矩阵逐层误差补偿）\n【追问】校准集要多少？\n答：512-1024 条算每层 Hessian（AWQ 只需 128 条激活统计）；校准数据分布要贴近业务，否则 domain gap 掉点\n【追问】和 AWQ 怎么选？\n答：精度优先 AWQ（保护显著权重通道）、吞吐优先 GPTQ+Marlin；低并发两者差距不大，高并发 Marlin 优势明显',
  'AWQ': '激活感知量化：按激活分布挑选重要权重通道保护（INT4）\n【追问】AWQ 和 GPTQ 的区别？\n答：AWQ 基于激活分布保护 1% 显著权重通道，校准成本低、精度稳；GPTQ 基于 Hessian 逐层误差补偿，配 Marlin 高并发吞吐更高。精度优先 AWQ、吞吐优先 GPTQ\n【追问】量化过程中遇到什么问题？\n答：①校准集不足 → MoE 专家路由稀疏精度掉点 → 按路由分布重采样 ②敏感专家统一 INT4 后 PPL 升幅差异可达 10× → top-3 专家 FP16 回退，PPL 升幅从 >1.5 压到 <0.5 ③低并发 INT4 因 dequant 开销接近 BF16',
  'Marlin': 'GPTQ 专用的高效 INT4 推理内核，A100 上有明显加速\n【追问】优势多大？\n答：高并发吞吐约 2-3×（vs BF16）；低并发因 dequantization 开销接近 BF16——硬件决定路线（A100 无 FP8 Tensor Core）',
  'bitsandbytes': 'PyTorch 量化库，支持 INT8/INT4 加载\n【追问】和 GPTQ/AWQ 区别？\n答：bitsandbytes 是运行时量化（加载时转换，不重写权重）；GPTQ/AWQ 是离线量化（预计算并保存量化权重，推理更高效）',
  '校准集': '量化时用于拟合统计量/误差补偿的数据集\n【追问】怎么构建？\n答：235B 项目混合 1024 条=通用 70%（中英文开源）+领域 30%（平台历史推理 query）；AWQ 128 条激活统计、GPTQ 512-1024 条算 Hessian；按 MoE 路由分布重采样保证专家覆盖；领域占比 0→30% 行业 query PPL 降 0.3-0.5',
  'PPL': '困惑度 perplexity：衡量生成质量，越低越好\n【追问】量化评估怎么用？\n答：per-layer PPL 升幅识别敏感层/专家（双指标之一）；235B 整体升幅从 >1.5 控制在 <0.5、任务精度损失 <1%',
  'TTFT': '首 token 延迟：从请求到输出第一个 token 的时间\n【追问】你的实测数据？\n答：StarVLA 104ms 均值/120ms P95；235B P50 123ms（4×A100 TP=4）。瓶颈分解：网络→prefill→decode→回传',
  'P99': '99% 请求延迟上限，衡量长尾延迟\n【追问】为什么看 P99 不看均值？\n答：均值掩盖长尾，P99 反映最差体验。RAG 端到端 P99 3-5s，瓶颈排序：生成 2-4s > reranker 300-500ms > embedding 80-150ms > 检索 <50ms',
  'TP': '张量并行：权重按卡切分、每步 all-reduce 同步的多卡推理方式\n【追问】和 device_map 的本质区别？\n答：device_map 是模型层级切分、每层跨卡通信延迟累积、负载不均易溢出；TP 是张量层级切分、同一层沿列/行切到多卡、all-reduce 通信量可控。122B 决策：原型走 device_map、线上走 vLLM TP=4',
  'EP': '专家并行：MoE 的 expert 分布到多卡\n【追问】怎么配置？\n答：vLLM 自动管理 expert 跨卡放置（TP+EP+DP 组合降路由跨卡延迟），无需显式配置',
  'device_map': 'Transformers 自动切分：模型层级跨卡加载\n【追问】和 vLLM TP 怎么分工？\n答：device_map 配置简单适合快速验证出数；线上推理选 vLLM TP=4（通信可控、负载均衡）——「原型验证走 device_map、线上推理选 TP=4」',
  'NCCL': 'NVIDIA 多 GPU 通信库，分布式训练/推理的关键依赖\n【追问】踩过什么坑？\n答：平台劫持 NCCL 导致 undefined symbol（libnccl 版本不一致）→ pip install nvidia-nccl-cu12 --no-deps + ctypes 预加载；torchrun RPC 与平台 NCCL 冲突 → LD_LIBRARY_PATH 预加载 libnccl.so.2',
  'Docker': '容器化技术：打包环境依赖，保证部署一致性\n【追问】有什么部署经验？\n答：版本兼容链锁定（CUDA→PyTorch→transformers→Gradio）+ pip --no-deps 精确锁版本 + 权重预下载断点续传 + 镜像不可变原则。车端 BSP 锁定约束更严格，但思路一样',
  '灰度发布': '分批放量升级，监控异常即回滚\n【追问】实际上线了吗？\n答：方案设计阶段未在生产落地（客户未开放 K8s 集群级流量治理权限）。设计：金丝雀副本先行 + 就绪探针含模型加载状态检查 + 通过后按流量权重逐步切流',
  'Prometheus': '开源监控系统：采集指标、告警、查询（Grafana 可视化）\n【追问】监控哪些指标？\n答：基于 vLLM /metrics：TTFT / P99 / GPU 利用率 / 请求队列深度；延迟分解（网络→prefill→decode→回传）定位瓶颈',
  'MoE': '专家混合架构：总参量大但每次只激活部分参数（如 235B-A22B）\n【追问】MoE 和稠密模型部署区别？\n答：①显存由总参量决定（所有 expert 都要加载）②激活小→推理延迟低 ③多卡需处理 expert 跨卡放置与 all-to-all 通信 ④量化时专家敏感度差异可达 10×，需混合精度回退',
  // ===== 智驾 / 系统 =====
  '端到端': '传感器原始输入直接输出动作，消除模块化误差传递\n【追问】和模块化对比？\n答：模块化感知→预测→规划→控制分步，可解释但误差传递；端到端黑盒但无误差累积。StarVLA 是视觉+语言→动作的端到端范式，与一段式智驾架构理念同构',
  'VLA': 'Vision-Language-Action：视觉+语言输入直接输出动作\n【追问】和智驾的关系？\n答：利用 LLM 常识与推理能力做驾驶决策，部分车企 JD 的 D2D/VLA 即此方向。我部署过 StarVLA（Action Token 非自回归，TTFT 104ms）',
  '世界模型': '学习环境物理规律的模型，用于仿真/预测/强化学习\n【追问】世界模型在自动驾驶怎么用？\n答：做环境预训练与闭环仿真，强化学习在虚拟环境探索最优策略——从「模仿人类驾驶」走向「自主探索最优策略」（某车企 R7 即此路线）',
  '诊断闭环': '检测异常→定位根因→降级恢复→验证→归档\n【追问】你项目里的对应设计？\n答：Agent Critic（异常信号→重试/换工具→最终校验→trace 归档）；自驾诊断 Agent 工具链（故障查询→信号分析→案例检索→报告生成）按此闭环设计',
  'ISO 26262': '汽车功能安全国际标准，ASIL A-D 分级\n【追问】你了解多少？\n答：坦诚未直接接触；了解 HARA 危害分析确定 ASIL 等级、拆解到软硬件安全需求。Agent Critic 是「防幻觉校验」，级别完全不同；入职后第一时间补齐',
  '功能仲裁': '多模块冲突决策时的裁决机制\n【追问】对应的迁移经验？\n答：Agent 入口分流（简单 RAG / 复杂 Agent）+ 多工具结果冲突时 Orchestrator 综合判断——多源信息融合决策的思路相通',
  'SDPA': 'PyTorch 内置的缩放点积注意力，flash_attn 缺失时的备选\n【追问】StarVLA 怎么用的？\n答：改模型文件去掉 flash_attn 硬编码、fallback SDPA——依赖缺失时的降级方案',
  'flash_attn': 'Flash Attention：减少 HBM 读写加速注意力计算\n【追问】缺失怎么办？\n答：降级 SDPA（PyTorch 内置）；StarVLA 部署即去硬编码改 fallback'
};


module.exports = { GLOSSARY, EXTRA };
